### ISSUE TITLE
Swadl not working in Google Chrome

### ISSUE THREAD

**Issue by jethroborsje** [ehearty/Swadl#1] opened 2015-10-08 07:06 UTC
It seems like Swadl is not working in Google Chrome. It just shows a white page underneath the green bar.

**Comment by ehearty** [comment] 2015-10-08 14:13
Thanks, I'll check it and get back to you.

**Comment by ehearty** [comment] 2015-10-08 14:19
Can I get more information? Is the demo page not working, or is it not
working when you check Swadl out and try to host it on your local web
server? Any debugging info that you see in the console log of the web
inspector frame would also be of help.

Thanks,
Elena.

**Comment by ehearty** [comment] 2015-10-08 15:07
It occurred to me that I think I know what the problem is. Are you trying
to view the wadl.html outside of a web server? If you are, then the rest of
the page will be blank because you can't make an ajax request to the file
system.

If you view the page through a web server, such as apache or nginx, and
then view wadl.html through "http://localhost/YOURPATH/wadl.html" then it
should be able to access the resources correctly.

Please let me know if this helps.

Thanks,
Elena.

**Comment by ehearty** [comment] 2016-01-20 15:35
Never heard back, so closing this issue. Please reopen if you continue to have problems.

**Closed as completed by ehearty** 2016-01-20 15:35 UTC
